import type { Metadata } from "next";
import "./globals.css";
import ConvexClientProvider from "@/components/ConvexClientProvider";
import { ClerkProvider } from "@clerk/nextjs";
import { SiteHeader } from "@/components/SiteHeader";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/convex.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <ClerkProvider dynamic>
          <ConvexClientProvider>
            <div className="flex min-h-screen flex-col">
              <SiteHeader />
              <main className="flex-1 flex justify-center">
                <div className="w-full max-w-3xl px-4 py-8">{children}</div>
              </main>
              <Toaster />

            </div>
          </ConvexClientProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
